name: statuschecker
on:
    workflow_dispatch:
    schedule:
       - cron: '*/5 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Python dependencies
        run: |
          pip install -U prefect==2.* influxdb-client requests httpx[http2]

      - name: Prefect Cloud login
        run: |
          prefect config set PREFECT_API_KEY=${{secrets.PREFECT_API_KEY}}
          prefect cloud workspace set --workspace "${{secrets.PREFECT_WORKSPACE}}"

      - name: statuschecks
        run: |
          export PYTHONPATH="${PYTHONPATH}"
          python status_check.py "${{secrets.INFLUXDB_TOKEN}}" "${{secrets.INFLUXDB_BUCKET}}" "${{secrets.INFLUXDB_URL}}"
